import {test} from 'node:test';
import assert from 'node:assert/strict';
import {parseAmount,totals,newLedger,recordSnapshot,validateLedger,csv,type Account} from '../lib/ledger.ts';
const account=(id:string,cents:number|null,group:Account['group']='Liquid assets'):Account=>({id,name:id,group,cents,updatedAt:'2026-09-08T00:00:00.000Z',note:'',archived:false});
test('decimal input is exact and rejects ambiguous or invalid money',()=>{assert.equal(parseAmount('1,234.56'),123456);assert.equal(parseAmount('-0.29'),-29);assert.equal(parseAmount('0'),0);assert.equal(parseAmount(''),null);for(const bad of ['1,2','1.234','1e3','Infinity','abc','--2'])assert.throws(()=>parseAmount(bad));});
test('assets minus debts uses integer cents, supports card credits, and excludes archived accounts',()=>{const r=totals([account('cash',100000),account('owed',20000,'Receivables'),account('invest',50000,'Investments'),account('cards',40000,'Credit cards'),{...account('old',999999),archived:true}]);assert.equal(r.net,130000);assert.equal(r.assets,170000);assert.equal(totals([account('credit',-100,'Credit cards')]).net,100);assert.equal(totals([account('unknown',null)]).missing,1);});
test('new snapshots do not mutate old balances and backup round trips',()=>{const a=account('cash',100);const first=recordSnapshot(newLedger(),[a],'2026-09-08T00:00:00.000Z');a.cents=200;assert.equal(first.snapshots[0].accounts[0].cents,100);const second=recordSnapshot(first,[a],'2026-09-09T00:00:00.000Z');assert.equal(second.snapshots[0].accounts[0].cents,100);assert.equal(validateLedger(JSON.parse(JSON.stringify(second))).snapshots.length,2);});
test('restore rejects invalid versions, duplicated ids, unsafe values and unordered history',()=>{const d=recordSnapshot(newLedger(),[account('cash',1)]);for(const bad of [{...d,version:2},{...d,accounts:[account('same',1),account('same',2)]},{...d,accounts:[account('bad',NaN)]},{...d,accounts:[{...account('bad',1),group:'Unknown'}]},{...d,snapshots:[{...d.snapshots[0],at:'invalid'}]}])assert.throws(()=>validateLedger(bad));});
test('Excel export escapes quotes and guards spreadsheet formulas',()=>{const d=recordSnapshot(newLedger(),[{...account('id',123),name:'=HYPERLINK("x")',note:'hello, world'}]);const s=csv(d);assert.match(s,/"'=HYPERLINK\(""x""\)"/);assert.match(s,/"1.23"/);assert.match(s,/"hello, world"/);});
