'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {Wallet,History,Shield,Plus,ArrowLeft,Download,Upload,ChevronRight,Check,Archive,Smartphone,CloudOff} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {groups,money,newLedger,parseAmount,totals,recordSnapshot,validateLedger,csv,type Account,type Ledger,type Group,type Snapshot} from '@/lib/ledger';
import {readLedger,writeLedger} from '@/lib/storage';
const date=(s:string)=>new Date(s).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
const stamp=(s:string)=>new Date(s).toLocaleString('en-US',{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'});
const errorText=(e:unknown)=>e instanceof Error?e.message:'Something went wrong. Please try again.';
function download(content:string,type:string,name:string) {const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
export default function Home(){
 const [data,setData]=useState<Ledger>(newLedger),[ready,setReady]=useState(false),[fatal,setFatal]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const [tab,setTab]=useState('overview'),[edit,setEdit]=useState(false),[draft,setDraft]=useState<Record<string,string>>({}),[checked,setChecked]=useState<Set<string>>(new Set());
 const [account,setAccount]=useState<Account|null>(null),[detail,setDetail]=useState<Snapshot|null>(null),[restore,setRestore]=useState<Ledger|null>(null),[archive,setArchive]=useState<Account|null>(null),[discard,setDiscard]=useState(false);
 const [offline,setOffline]=useState(false),[offlineReady,setOfflineReady]=useState(false),[installed,setInstalled]=useState(false),[backupAt,setBackupAt]=useState<string|null>(null);
 useEffect(()=>{readLedger().then(d=>{setData(d);setReady(true);}).catch(e=>setFatal(errorText(e)));
  try{setBackupAt(localStorage.getItem('balance-pocket-backup'));}catch{}
  setInstalled(window.matchMedia('(display-mode: standalone)').matches||Boolean((navigator as Navigator&{standalone?:boolean}).standalone));
  const connectivity=()=>setOffline(!navigator.onLine);connectivity();window.addEventListener('online',connectivity);window.addEventListener('offline',connectivity);
  const receive=(e:MessageEvent)=>{if(e.data?.type==='OFFLINE_READY')setOfflineReady(true);};navigator.serviceWorker?.addEventListener('message',receive);
  if('serviceWorker' in navigator && process.env.NODE_ENV==='production')navigator.serviceWorker.register('/sw.js').then(async r=>{await navigator.serviceWorker.ready;r.active?.postMessage({type:'STATUS'});}).catch(()=>{});
  return()=>{window.removeEventListener('online',connectivity);window.removeEventListener('offline',connectivity);navigator.serviceWorker?.removeEventListener('message',receive);};
 },[]);
 useEffect(()=>{if(!edit&&!account)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[edit,account]);
 async function commit(next:Ledger,success:string){if(busy||!ready)return false;setBusy(true);setError('');try{setData(await writeLedger(next,data.revision));setMessage(success);return true;}catch(e){setError(errorText(e));return false;}finally{setBusy(false);}}
 const active=data.accounts.filter(a=>!a.archived),summary=totals(data.accounts),previous=data.snapshots.length>1?totals(data.snapshots.at(-2)!.accounts):null;
 function beginEdit(){setDraft(Object.fromEntries(active.map(a=>[a.id,a.cents===null?'':(a.cents/100).toFixed(2)])));setChecked(new Set());setError('');setMessage('');setEdit(true);}
 function startAccount(a?:Account){setAccount(a?{...a}:{id:crypto.randomUUID(),name:'',group:'Liquid assets',cents:null,updatedAt:null,note:'',archived:false});setError('');setMessage('');}
 async function saveBalances(e:FormEvent){e.preventDefault();setError('');try{
  const at=new Date().toISOString();const rows=data.accounts.map(a=>!a.archived&&checked.has(a.id)?{...a,cents:parseAmount(draft[a.id]),updatedAt:draft[a.id].trim()?at:null}:a);
  if(!checked.size)throw Error('Enter a balance or mark an account as checked first.');
  if(await commit(recordSnapshot(data,rows,at),'Balances saved on this device.'))setEdit(false);
 }catch(e){setError(errorText(e));}}
 async function saveAccount(e:FormEvent){e.preventDefault();if(!account)return;const name=account.name.trim();if(!name){setError('Enter an account name.');return;}if(data.accounts.some(a=>a.id!==account.id&&!a.archived&&a.name.toLowerCase()===name.toLowerCase())){setError('An active account already has this name.');return;}
  const exists=data.accounts.some(a=>a.id===account.id);const rows=exists?data.accounts.map(a=>a.id===account.id?{...account,name}:a):[...data.accounts,{...account,name}];
  if(await commit({...data,accounts:rows},exists?'Account updated.':'Account added. Use Update balances to enter its amount.'))setAccount(null);
 }
 async function importFile(file:File|undefined){if(!file)return;setError('');try{if(file.size>20_000_000)throw Error('Choose a backup smaller than 20 MB.');const value=JSON.parse(await file.text());setRestore(validateLedger(value));}catch(e){setError(errorText(e));}}
 function backup(){download(JSON.stringify(data,null,2),'application/json',`balance-pocket-${new Date().toISOString().slice(0,10)}.json`);const at=new Date().toISOString();setBackupAt(at);try{localStorage.setItem('balance-pocket-backup',at);}catch{}setMessage('Backup download started. Save it in Files → On My iPhone, then check that the file is there.');}
 const dirtyExit=()=>{if(edit&&checked.size||account)setDiscard(true);else setEdit(false);};
 const notices=<>{error&&<div className="notice error" role="alert">{error}</div>}{message&&<div className="notice success" role="status">{message}</div>}</>;
 return <main className="shell"><header className="topbar"><span className="brand-icon" aria-hidden="true">b.</span><h1>Balance Pocket</h1><span className="device-label"><Shield size={13}/>{offline?'Offline':'On this device'}</span></header>
 {fatal?<section className="panel"><h2>Unable to open your data</h2><p className="muted">{fatal}</p><button className="secondary" onClick={()=>location.reload()}>Try again</button></section>:!ready?<p className="muted" role="status">Opening your balance sheet…</p>:<>
 {edit?<><div className="section-heading"><button className="text-button" onClick={dirtyExit}><ArrowLeft size={18}/>Back</button><h2>Update balances</h2></div><p className="muted intro">Enter current balances in USD. Unchanged accounts keep their previous check date. Negative amounts are allowed for overdrafts or card credits.</p>{notices}<form onSubmit={saveBalances}><fieldset disabled={busy}><button type="button" className="secondary mark-all" onClick={()=>setChecked(new Set(active.filter(a=>draft[a.id].trim()).map(a=>a.id)))}><Check size={16}/>Mark all entered balances as checked</button>{groups.map((g,i)=><section className="panel edit-group" key={g}><header><span className={'category-dot dot-'+i}/><h3>{g}</h3></header>{active.filter(a=>a.group===g).map(a=><div className="balance-row" key={a.id}><label htmlFor={'balance-'+a.id}>{a.name}<small>{a.updatedAt?'Checked '+date(a.updatedAt):'No balance yet'}</small></label><div className="entry-controls"><span className="amount-input"><span>$</span><input id={'balance-'+a.id} inputMode="decimal" type="text" autoComplete="off" placeholder="0.00" value={draft[a.id]} onChange={e=>{setDraft({...draft,[a.id]:e.target.value});setChecked(new Set([...checked,a.id]));}}/></span><button type="button" className={'check-button '+(checked.has(a.id)?'is-checked':'')} aria-label={'Mark '+a.name+' as checked'} aria-pressed={checked.has(a.id)} onClick={()=>{const next=new Set(checked);if(next.has(a.id))next.delete(a.id);else next.add(a.id);setChecked(next);}}><Check size={18}/></button></div></div>)}</section>)}<div className="save-bar"><span>{checked.size} account{checked.size===1?'':'s'} checked</span><button className="primary" type="submit" disabled={!checked.size||busy}>{busy?'Saving…':'Save snapshot'}</button></div></fieldset></form></>
 :account?<><div className="section-heading"><button className="text-button" onClick={dirtyExit}><ArrowLeft size={18}/>Back</button><h2>{data.accounts.some(a=>a.id===account.id)?'Account details':'Add account'}</h2></div>{notices}<form className="panel account-form" onSubmit={saveAccount}><fieldset disabled={busy}><label>Account name<input required maxLength={80} value={account.name} placeholder="e.g. Apple Savings" onChange={e=>setAccount({...account,name:e.target.value})}/></label><label id="group-label">Category</label><Select value={account.group} onValueChange={v=>v&&setAccount({...account,group:v as Group})}><SelectTrigger className="category-select" aria-labelledby="group-label"><SelectValue/></SelectTrigger><SelectContent>{groups.map(g=><SelectItem value={g} key={g}>{g}</SelectItem>)}</SelectContent></Select><label>Notes <span className="muted">(optional)</span><textarea maxLength={1000} rows={3} value={account.note} placeholder="Anything you want to remember" onChange={e=>setAccount({...account,note:e.target.value})}/></label>{account.cents!==null&&<p className="muted">Current balance: {money(account.cents)} · {account.updatedAt?date(account.updatedAt):'Not checked'}</p>}<button className="primary" type="submit">{busy?'Saving…':'Save account'}</button>{data.accounts.some(a=>a.id===account.id)&&<button type="button" className="text-button danger" onClick={()=>setArchive(account)}><Archive size={16}/>Archive account</button>}</fieldset></form>{data.snapshots.some(s=>s.accounts.some(a=>a.id===account.id&&a.cents!==null))&&<section className="panel detail-history"><h3>Balance history</h3>{data.snapshots.filter(s=>s.accounts.some(a=>a.id===account.id&&a.cents!==null)).slice(-12).reverse().map(s=><div className="history-row" key={s.id}><span>{stamp(s.at)}</span><strong>{money(s.accounts.find(a=>a.id===account.id)!.cents!)}</strong></div>)}</section>}</>
 :<Tabs value={tab} onValueChange={v=>{setTab(String(v));setDetail(null);setError('');setMessage('');}}><TabsList className="bottom-nav" aria-label="Main navigation"><TabsTrigger value="overview"><Wallet/>Overview</TabsTrigger><TabsTrigger value="history"><History/>History</TabsTrigger><TabsTrigger value="settings"><Shield/>Your data</TabsTrigger></TabsList>{notices}<TabsContent value="overview"><section className="hero"><p className="eyebrow">YOUR PERSONAL BALANCE SHEET</p><h2>Net worth</h2><div className="net-value">{money(summary.net).split('.')[0]}<span>.{money(summary.net).split('.')[1]}</span></div><p>{!active.length?'A clear picture starts with your accounts.':summary.missing?`${summary.missing} account${summary.missing===1?' has':'s have'} no balance yet. Totals are incomplete.`:previous?`${money(summary.net-previous.net)} since the previous snapshot`:'Your first chapter, recorded.'}</p><div className="hero-totals"><div><span>Total assets</span><strong>{money(summary.assets)}</strong></div><div><span>Total debt</span><strong>{money(summary.debt)}</strong></div></div></section><div className="section-heading"><div><h2>Your accounts</h2><p className="muted">{active.length} account{active.length===1?'':'s'} · USD</p></div>{active.length>0&&<button className="primary" onClick={beginEdit}>Update balances</button>}</div>{active.length===0?<section className="panel onboarding"><span className="empty-icon"><Wallet size={25}/></span><h3>Make this balance sheet yours</h3><p className="muted">Add your checking, savings, investments, money owed to you, and credit cards. Enter their balances whenever you’re ready.</p><button className="primary" onClick={()=>startAccount()}><Plus size={18}/>Add your first account</button><p className="muted">No bank connections. No automatic imports.</p></section>:<><div className="groups">{groups.map((g,i)=><section className="panel" key={g}><header><span className={'category-dot dot-'+i}/><h3>{g}</h3><strong>{money(active.filter(a=>a.group===g).reduce((s,a)=>s+(a.cents??0),0))}</strong></header>{active.filter(a=>a.group===g).map(a=><button className="account-row" key={a.id} onClick={()=>startAccount(a)}><span>{a.name}<small>{a.updatedAt?'Checked '+date(a.updatedAt):'Balance not entered'}</small></span><strong>{a.cents===null?'—':money(a.cents)}</strong><ChevronRight size={15}/></button>)}{!active.some(a=>a.group===g)&&<p className="muted">No accounts here yet.</p>}</section>)}</div><button className="secondary add-button" onClick={()=>startAccount()}><Plus size={18}/>Add account</button></>}<p className="privacy-note"><Shield size={13}/> Your balances stay on this device.</p>{data.snapshots.length>0&&(!backupAt||Date.now()-Date.parse(backupAt)>604800000)&&<div className="backup-nudge"><div><strong>Keep a copy safe</strong><p className="muted">A backup protects your history if this app’s data is cleared.</p></div><button className="secondary" onClick={backup}>Back up</button></div>}</TabsContent>
 <TabsContent value="history"><div className="section-heading"><h2>{detail?'Snapshot details':'Your progress'}</h2>{detail&&<button className="text-button" onClick={()=>setDetail(null)}><ArrowLeft size={16}/>All history</button>}</div>{detail?<section className="panel"><h3>{stamp(detail.at)}</h3><p className="snapshot-net">{money(totals(detail.accounts).net)} <span>net worth</span></p>{detail.accounts.filter(a=>!a.archived).map(a=><div className="history-row" key={a.id}><span>{a.name}<small>{a.group}</small></span><strong>{a.cents===null?'Not entered':money(a.cents)}</strong></div>)}</section>:data.snapshots.length===0?<section className="panel onboarding"><History size={30}/><h3>Your history starts here</h3><p className="muted">Save your first balance update to create a snapshot. Future updates will show how your assets, debt, and net worth change.</p>{active.length>0&&<button className="primary" onClick={beginEdit}>Update balances</button>}</section>:<><section className="panel trend"><header><h3>Net worth over time</h3><span className="muted">{data.snapshots.length} snapshots</span></header>{data.snapshots.length>1?<Trend snapshots={data.snapshots}/>:<p className="muted">Your first snapshot is saved. Save another to see your trend.</p>}</section><section className="panel snapshot-list">{[...data.snapshots].reverse().map(s=><button className="account-row" key={s.id} onClick={()=>setDetail(s)}><span>{stamp(s.at)}<small>Assets {money(totals(s.accounts).assets)} · Debt {money(totals(s.accounts).debt)}{totals(s.accounts).missing?' · Incomplete':''}</small></span><strong>{money(totals(s.accounts).net)}</strong><ChevronRight size={16}/></button>)}</section></>}</TabsContent>
 <TabsContent value="settings"><div className="section-heading"><h2>Your data, in your pocket</h2></div><section className="panel settings-section"><Shield size={25}/><h3>Saved only on this device</h3><p className="muted">Account names, balances, notes, and history are stored in this app’s device storage. They aren’t sent to a server. Other devices and browser profiles have separate data.</p><p className="muted">Clearing website data or losing your phone can erase your records. Back up regularly. Anyone with access to this unlocked app can view your balances.</p></section><section className="panel settings-section"><h3>Backup & export</h3><p className="muted">Save a full backup in Files → <strong>On My iPhone</strong> to keep it on your phone. Choosing iCloud Drive or another cloud folder stores that exported copy there.</p><div className="button-stack"><button className="primary" onClick={backup}><Download size={18}/>Download full backup</button><button className="secondary" onClick={()=>{download(csv(data),'text/csv;charset=utf-8', 'balance-pocket-history.csv');setMessage('CSV download started. This is for Excel; use a full backup to restore the app.');}}><Download size={18}/>Export history for Excel</button></div><p className="muted">{backupAt?'Last backup requested '+stamp(backupAt)+'. Verify it was saved in Files.':'No backup requested yet.'}</p><label className="restore-file"><Upload size={18}/>Restore a full backup<input type="file" accept=".json,application/json" onChange={e=>{void importFile(e.target.files?.[0]);e.target.value='';}}/></label><p className="muted">Restore replaces current records after you review and confirm.</p></section><section className="panel settings-section"><Smartphone size={25}/><h3>{installed?'Installed on your Home Screen':'Add to your iPhone'}</h3><ol><li>Open this app’s link in Safari.</li><li>Tap Share, then Add to Home Screen.</li><li>Open the Home Screen app before entering your balances.</li></ol><p className="muted">If you entered data in Safari first, export a backup there and restore it in the Home Screen app if needed.</p><p className={'offline-state '+(offlineReady?'good':'')}><CloudOff size={17}/>{offlineReady?'Ready to open offline':'Offline setup pending. Keep the app open while online.'}</p></section>{data.accounts.some(a=>a.archived)&&<section className="panel settings-section"><h3>Archived accounts</h3><p className="muted">Excluded from current totals. Past snapshots are preserved.</p>{data.accounts.filter(a=>a.archived).map(a=><div className="history-row" key={a.id}><span>{a.name}</span><button disabled={busy} className="secondary" onClick={()=>void commit(recordSnapshot(data,data.accounts.map(x=>x.id===a.id?{...x,archived:false}:x)),'Account restored.')}>Restore account</button></div>)}</section>}</TabsContent></Tabs>}
 </>}
 <AlertDialog open={Boolean(restore)} onOpenChange={v=>!v&&!busy&&setRestore(null)}><AlertDialogContent><AlertDialogTitle>Replace your current data?</AlertDialogTitle><AlertDialogDescription>This backup contains {restore?.accounts.length} accounts and {restore?.snapshots.length} snapshots. Your current records will be replaced. Download a backup first if you want to keep them.</AlertDialogDescription>{error&&<p className="error notice" role="alert">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancel</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async()=>{if(restore&&await commit({...restore,revision:data.revision},'Backup restored on this device.'))setRestore(null);}}>Replace & restore</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={Boolean(archive)} onOpenChange={v=>!v&&!busy&&setArchive(null)}><AlertDialogContent><AlertDialogTitle>Archive {archive?.name}?</AlertDialogTitle><AlertDialogDescription>It will be excluded from current totals. Past snapshots stay unchanged. You can restore it from Your data.</AlertDialogDescription>{error&&<p className="error notice" role="alert">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancel</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async()=>{if(archive&&await commit(recordSnapshot(data,data.accounts.map(a=>a.id===archive.id?{...a,archived:true}:a)),'Account archived.')){setArchive(null);setAccount(null);}}}>Archive</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={discard} onOpenChange={setDiscard}><AlertDialogContent><AlertDialogTitle>Discard this edit?</AlertDialogTitle><AlertDialogDescription>Your saved balances and history will remain unchanged.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Keep editing</AlertDialogCancel><AlertDialogAction onClick={()=>{setEdit(false);setAccount(null);setDiscard(false);setError('');}}>Discard changes</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </main>;
}
function Trend({snapshots}:{snapshots:Snapshot[]}) {const items=snapshots.slice(-30),values=items.map(s=>totals(s.accounts).net);const min=Math.min(...values),max=Math.max(...values),range=max-min||100;
 const points=values.map((v,i)=>`${20+i/(values.length-1)*580},${140-(v-min)/range*110}`).join(' ');
 return <><div className="trend-values"><strong>{money(values.at(-1)!)}</strong><span className="muted">Latest net worth</span></div><svg className="trend-svg" viewBox="0 0 620 170" role="img" aria-label={`Net worth from ${money(values[0])} to ${money(values.at(-1)!)} across the last ${items.length} snapshots. Detailed values are listed below.`}><line x1="20" y1="150" x2="600" y2="150" stroke="#dce3ee"/><polyline points={points} fill="none" stroke="#164ad9" strokeWidth="3" strokeLinejoin="round"/>{values.map((v,i)=><circle key={items[i].id} cx={20+i/(values.length-1)*580} cy={140-(v-min)/range*110} r="4" fill="#164ad9"/>)}</svg><div className="chart-dates"><span>{date(items[0].at)}</span><span>{date(items.at(-1)!.at)}</span></div><p className="muted">Last {items.length} snapshots · equally spaced updates</p></>;
}
